/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: Jay (https://sketchfab.com/jstaggs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tropical-drink-22e4bee9f7c84e49aad9d85d1233f241
Title: Tropical Drink
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.68}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.glass_glass_0.geometry} material={materials.glass} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.drink_drink_0.geometry} material={materials.drink} position={[0, -56.06, -0.39]} rotation={[-1.58, 0, 0]} scale={[100, 100, 121.59]} />
          <mesh geometry={nodes.umbrellatop_umbrella_0.geometry} material={materials.umbrella} position={[26.53, -55.5, 258.4]} rotation={[-Math.PI / 2, -0.05, 0]} scale={128.93} />
          <mesh geometry={nodes.umbrellastick_stick_0.geometry} material={materials.stick} position={[-100.01, 301.84, -12.62]} rotation={[-Math.PI / 2, -0.33, 0]} scale={[2.58, 2.5, 85.71]} />
          <mesh geometry={nodes.straw_straw_0.geometry} material={materials.straw} position={[9.97, 274.78, 103.52]} rotation={[-1.07, -0.06, -2.9]} scale={[3.83, 3.71, 88.17]} />
          <mesh geometry={nodes.orangerind_orangerind_0.geometry} material={materials.material_0} position={[-100, 258.16, 67.79]} rotation={[-0.06, 0.48, 0.54]} scale={[70.18, 70.18, 15.18]} />
          <mesh geometry={nodes.orangecenter_orangecenter_0.geometry} material={materials.orangecenter} position={[-100, 258.17, 67.79]} rotation={[-0.06, 0.48, 0.54]} scale={[61.65, 61.65, 13.49]} />
          <mesh geometry={nodes.cherry_cherry_0.geometry} material={materials.cherry} position={[-90.23, 261.23, 22.21]} rotation={[1.5, 0.11, 0]} scale={[-18.96, 18.96, 18.96]} />
          <mesh geometry={nodes.cherrystem_cherrystem_0.geometry} material={materials.cherrystem} position={[-87.4, 245.96, 24.97]} rotation={[1.5, 0.11, 0]} scale={[-18.96, 18.96, 29.11]} />
          <mesh geometry={nodes.cherry2_cherry001_0.geometry} material={materials['cherry.001']} position={[-45.94, 256.12, 71.18]} rotation={[1.63, 0.12, -1.02]} scale={[-20.5, 20.5, 20.5]} />
          <mesh geometry={nodes.cherrystem2_cherrystem001_0.geometry} material={materials['cherrystem.001']} position={[-41.8, 239.61, 70.14]} rotation={[1.63, 0.12, -1.02]} scale={[-20.5, 20.5, 31.47]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
